### ISSUE TITLE
[Question] Is the support for version 1.20.4 being planned?

### ISSUE THREAD

**Issue by fitwoMIPT** [Chikorita-Lover/Caffeinated#10]
I like making use of pretty much useless items in minecraft by mods. This mod is really neat and makes exploring jungles worth it. However, my small friend group server is working on 1.20.4 and we can't add this mod. 

I wanted to ask if there will be support for newer versions?

**Comment by Chikorita-Lover** [comment]
Thanks for reaching out! There weren't any plans to port to 1.20.4 mostly because of the lack of other content mods that _have_ ported to 1.20.4.
If you wish, I could look into making a quick port. I'm not very familiar with any changes made in 1.20.3, but I wouldn't imagine it would take too long.

**Comment by fitwoMIPT** [comment]
Thank you for the reply! My friends decided to switch to 1.20.1 since most of the mods are there, so no need now, but thanks!
