### ISSUE TITLE
Coffee Bush Genertation on Server

### ISSUE THREAD

**Issue by heyrise** [Chikorita-Lover/Caffeinated#13]
Hi,
I'm struggling to get coffee bushes to generate on a server. 
Locally on the same seed I can find them pretty easily. I don't see anything in the logs to suggest Caffeinated hasn't loaded correctly. I'm using the same version of Farmer's Delight both locally and on the server. 
Dropping into Creative Mode on the server I can find the associated items with the plugin so I believe it's loaded. 
Is there anything else I can do to check my end that it's working correctly, to help troubleshoot what the issue might be? 

Any help would be greatly appreciated.
Many Thanks

**Comment by Chikorita-Lover** [comment]
Hi, thanks for reaching out - what version of Caffeinated are you using and what Minecraft version are you on? Also, are there any mods you've installed that may tweak world generation? Issues related to this should be fixed on the latest version for 1.21.x unless I missed something.

**Comment by heyrise** [comment]
Found the issue :)
I had just listed my client and server version. Went to then list the mods on the server. And highlight any world-gen mods. Noticed I had 2 versions of Geophilic installed. Complete missed this before.
Removed the older of the two versions, and restarted the server. Generated some new forest chunks and Coffee bean shrubs have generated. 
Sorry to have wasted your time.

**Comment by Chikorita-Lover** [comment]
Oh no worries! Glad you were able to figure it out!
