### ISSUE TITLE
Coffee Bushes wont generate

### ISSUE THREAD

**Issue by J-F2** [Chikorita-Lover/Caffeinated#4]
I've looked through my world for a while now, and on the 1.20 version of this mod coffee bushes wont generate.

**Comment by Chikorita-Lover** [comment]
Are you sure you're searching in the right place? Coffee shrubs are only found in jungle biomes - not just any biome! I've checked myself and I was able to find coffee shrubs. Are you able to find coffee shrubs in jungle biomes?

**Comment by Chikorita-Lover** [comment]
Here's the seed I used: `-3703175589083716388`

**Comment by J-F2** [comment]
alright, thank you. i was able to find some, theyre rather rare. ill have to see if this functiions with my modpack.
